'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Pencil, Plus, Trash2, X } from 'lucide-react'

const sections: Record<string, { title: string; description: string; fields: { key: string; label: string; type?: string; required?: boolean }[] }> = {
  categorias: { title: 'Categorias', description: 'Gerencie os temas editoriais do portal.', fields: [{ key: 'name', label: 'Nome', required: true }, { key: 'slug', label: 'Slug' }, { key: 'order', label: 'Ordem', type: 'number' }] },
  envios: { title: 'Envios dos leitores', description: 'Analise e organize sugestões enviadas pela comunidade.', fields: [{ key: 'senderName', label: 'Nome do leitor', required: true }, { key: 'title', label: 'Título', required: true }, { key: 'description', label: 'Descrição', type: 'textarea', required: true }, { key: 'whatsapp', label: 'WhatsApp' }, { key: 'email', label: 'E-mail' }, { key: 'location', label: 'Local' }, { key: 'status', label: 'Status' }] },
  obituario: { title: 'Obituário', description: 'Cadastre comunicados de falecimento.', fields: [{ key: 'fullName', label: 'Nome completo', required: true }, { key: 'deathDate', label: 'Data do falecimento', type: 'date', required: true }, { key: 'birthDate', label: 'Data de nascimento', type: 'date' }, { key: 'age', label: 'Idade', type: 'number' }, { key: 'wakeLocation', label: 'Local do velório' }, { key: 'wakeTime', label: 'Horário do velório' }, { key: 'burialLocation', label: 'Local do sepultamento' }, { key: 'burialTime', label: 'Horário do sepultamento' }, { key: 'message', label: 'Mensagem', type: 'textarea' }, { key: 'photoUrl', label: 'URL da foto' }] },
  classificados: { title: 'Classificados', description: 'Publique anúncios de compra, venda e serviços.', fields: [{ key: 'title', label: 'Título', required: true }, { key: 'description', label: 'Descrição', type: 'textarea', required: true }, { key: 'category', label: 'Categoria', required: true }, { key: 'price', label: 'Preço', type: 'number' }, { key: 'contactName', label: 'Nome de contato', required: true }, { key: 'whatsapp', label: 'WhatsApp', required: true }, { key: 'phone', label: 'Telefone' }, { key: 'location', label: 'Localização' }] },
  'guia-comercial': { title: 'Guia Comercial', description: 'Cadastre empresas e parceiros comerciais.', fields: [{ key: 'name', label: 'Nome da empresa', required: true }, { key: 'category', label: 'Categoria', required: true }, { key: 'description', label: 'Descrição', type: 'textarea', required: true }, { key: 'whatsapp', label: 'WhatsApp', required: true }, { key: 'phone', label: 'Telefone' }, { key: 'website', label: 'Site' }, { key: 'instagram', label: 'Instagram' }, { key: 'address', label: 'Endereço', required: true }, { key: 'workingHours', label: 'Horário de funcionamento' }, { key: 'logoUrl', label: 'URL do logo' }] },
  eventos: { title: 'Eventos', description: 'Mantenha a agenda da cidade atualizada.', fields: [{ key: 'title', label: 'Nome do evento', required: true }, { key: 'description', label: 'Descrição', type: 'textarea', required: true }, { key: 'eventDate', label: 'Data', type: 'date', required: true }, { key: 'eventTime', label: 'Horário', required: true }, { key: 'location', label: 'Local', required: true }, { key: 'organizer', label: 'Organizador' }, { key: 'whatsapp', label: 'WhatsApp' }, { key: 'imageUrl', label: 'URL da imagem' }] },
  empregos: { title: 'Empregos', description: 'Publique oportunidades profissionais.', fields: [{ key: 'company', label: 'Empresa', required: true }, { key: 'title', label: 'Título da vaga', required: true }, { key: 'description', label: 'Descrição', type: 'textarea', required: true }, { key: 'requirements', label: 'Requisitos', type: 'textarea' }, { key: 'salary', label: 'Salário' }, { key: 'benefits', label: 'Benefícios', type: 'textarea' }, { key: 'location', label: 'Localização' }, { key: 'contact', label: 'Contato', required: true }, { key: 'deadline', label: 'Prazo', type: 'date' }] },
}

export default function AdminSectionPage({ params }: { params: Promise<{ section: string }> }) {
  const [sectionKey, setSectionKey] = useState('')
  const [items, setItems] = useState<any[]>([])
  const [form, setForm] = useState<Record<string, any>>({})
  const [editing, setEditing] = useState<any>(null)
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(true)
  const config = sections[sectionKey]

  useEffect(() => { params.then(({ section }) => setSectionKey(section)) }, [params])
  useEffect(() => { if (!config) return; setLoading(true); fetch(`/api/admin/conteudo/${sectionKey}`).then((response) => response.ok ? response.json() : []).then(setItems).finally(() => setLoading(false)) }, [sectionKey, config])

  const visibleFields = useMemo(() => config?.fields ?? [], [config])
  function start(item?: any) { setEditing(item ?? null); setForm(item ? { ...item, deathDate: item.deathDate?.slice(0, 10), birthDate: item.birthDate?.slice(0, 10), eventDate: item.eventDate?.slice(0, 10), deadline: item.deadline?.slice(0, 10) } : {}); setOpen(true) }
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/admin/conteudo/${sectionKey}`, { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editing ? { ...form, id: editing.id } : form) }); if (!response.ok) { alert('Não foi possível salvar este registro.'); return }; const saved = await response.json(); setItems((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setOpen(false); setForm({}) }
  async function remove(id: string) { if (!confirm('Excluir este registro?')) return; const response = await fetch(`/api/admin/conteudo/${sectionKey}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); if (response.ok) setItems((current) => current.filter((item) => item.id !== id)) }

  if (!config) return <section className="rounded-2xl border border-slate-200 bg-white p-8"><h2 className="text-2xl font-black text-slate-950">Seção em configuração</h2><Link href="/admin" className="mt-5 inline-flex rounded-lg bg-[#0808F5] px-4 py-2 text-sm font-bold text-white">Voltar</Link></section>
  return <section className="flex flex-col gap-6">
    <div className="flex flex-col justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-6 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#0808F5]">Painel CMS</p><h2 className="mt-2 text-3xl font-black text-slate-950">{config.title}</h2><p className="mt-1 text-slate-500">{config.description}</p></div><button onClick={() => start()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#0808F5] px-4 py-3 text-sm font-bold text-white"><Plus size={17} /> Novo cadastro</button></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{loading ? <p className="p-8 text-slate-500">Carregando registros...</p> : items.length === 0 ? <div className="p-10 text-center"><p className="font-bold text-slate-700">Nenhum item cadastrado ainda</p><button onClick={() => start()} className="mt-4 font-bold text-[#0808F5]">Criar o primeiro cadastro</button></div> : <div className="divide-y divide-slate-100">{items.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 p-4"><div className="min-w-0"><p className="truncate font-bold text-slate-900">{item.name || item.title || item.fullName || item.company}</p><p className="truncate text-sm text-slate-500">{item.description || item.category || item.status || item.location || 'Registro cadastrado'}</p></div><div className="flex shrink-0 gap-2"><button onClick={() => start(item)} aria-label="Editar" className="rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-50"><Pencil size={16} /></button><button onClick={() => remove(item.id)} aria-label="Excluir" className="rounded-lg border border-red-100 p-2 text-red-600 hover:bg-red-50"><Trash2 size={16} /></button></div></div>)}</div>}</div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h3 className="text-xl font-black">{editing ? 'Editar cadastro' : 'Novo cadastro'}</h3><button type="button" onClick={() => setOpen(false)} aria-label="Fechar"><X /></button></div><div className="grid gap-4 sm:grid-cols-2">{visibleFields.map((field) => <label key={field.key} className={field.type === 'textarea' ? 'sm:col-span-2' : ''}><span className="mb-1 block text-sm font-bold text-slate-700">{field.label}</span>{field.type === 'textarea' ? <textarea required={field.required} value={form[field.key] ?? ''} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })} rows={4} className="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-[#0808F5]" /> : <input required={field.required} type={field.type ?? 'text'} value={form[field.key] ?? ''} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-[#0808F5]" />}</label>)}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-lg px-4 py-2 font-bold text-slate-600">Cancelar</button><button className="rounded-lg bg-[#0808F5] px-5 py-2 font-bold text-white">Salvar cadastro</button></div></form></div>}
  </section>
}
